# Generated by Django 5.2.1 on 2025-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_salon_remove_task_project_reservacion_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='salones/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='precio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
