# Generated by Django 5.2.1 on 2025-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_salon_ciudad_salon_imagen_salon_precio_salon_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='rating',
        ),
        migrations.AddField(
            model_name='salon',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
