# Generated by Django 5.2.1 on 2025-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_salon_ciudad_remove_salon_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='categoria',
            field=models.CharField(choices=[('reuniones', 'Reuniones'), ('expos', 'Expos'), ('fiestas', 'Fiestas')], default='reuniones', max_length=20),
        ),
    ]
