# Generated by Django 5.2.1 on 2025-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_salon_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='ciudad',
            field=models.CharField(default='CDMX', max_length=100),
        ),
    ]
