# Generated by Django 5.2.1 on 2025-08-09 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_salon_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
