# Generated by Django 5.2.1 on 2025-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_reservacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='reservacion',
            unique_together={('salon', 'fecha_reserva')},
        ),
    ]
