# Generated by Django 5.2.1 on 2025-08-11 05:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reservacion_pagada_alter_reservacion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
